server:
  port: 8081
  servlet:
    context-path: /rest/v1/api/order-service
spring:
  datasource:
    url: jdbc:h2:mem:orderservice;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true